Repository kookmin-sw/capstone-2022-06, pull requests merged in 2022-03, with the labels that each got.

#4 feature/#2(update)
  .gitignore
  .vsconfig
  Assets/Resources/Animations/Anim_LichMinion.controller
  UserSettings/EditorUserSettings.asset
  UserSettings/Layouts/default-2021.dwlt
Labels: documentation

#16 [추가] 스킬샷 범위 UI 추가
  Assets/Resources/Sprites.meta
  Assets/Resources/Sprites/Ability 1.psd
  Assets/Resources/Sprites/Ability 1.psd.meta
  Assets/Resources/Sprites/Ability 2.psd
  Assets/Resources/Sprites/Ability 2.psd.meta
  Assets/Resources/Sprites/Ability 3.psd
  Assets/Resources/Sprites/Ability 3.psd.meta
  Assets/Resources/Sprites/Arrow_Ability_Indicator_Blue.png
  Assets/Resources/Sprites/Arrow_Ability_Indicator_Blue.png.meta
  Assets/Resources/Sprites/Heal_Indicator_Blue.png
  Assets/Resources/Sprites/Heal_Indicator_Blue.png.meta
  Assets/Resources/Sprites/Range_Indicator_Blue.png
  Assets/Resources/Sprites/Range_Indicator_Blue.png.meta
  Assets/Scenes/Character.unity
  Assets/Scripts/Character/Ability.cs
Labels: new asset

#20 Feature/19 전장의 안개 기반 코드 작성
  .gitignore
  Assets/Resources/Materials.meta
  Assets/Resources/Materials/FogOfWar.mat
  Assets/Resources/Materials/FogOfWar.mat.meta
  Assets/Resources/Materials/ViewVisualisation.mat
  Assets/Resources/Materials/ViewVisualisation.mat.meta
  Assets/Resources/Textures.meta
  Assets/Resources/Textures/OpenFogTexture.renderTexture
  Assets/Resources/Textures/OpenFogTexture.renderTexture.meta
  Assets/Scripts/Character/FieldOfView.cs
  Assets/Scripts/Character/FieldOfView.cs.meta
  Assets/Scripts/ExLibrary.meta
  Assets/Scripts/ExLibrary/Geometry.cs
  Assets/Scripts/ExLibrary/Geometry.cs.meta
  Assets/Scripts/Field.meta
  Assets/Scripts/Field/FogProjector.cs
  Assets/Scripts/Field/FogProjector.cs.meta
  Assets/Shaders.meta
  Assets/Shaders/FogProjection.shader
  Assets/Shaders/FogProjection.shader.meta
  Assets/Shaders/GaussianBlur.shader
  Assets/Shaders/GaussianBlur.shader.meta
  ProjectSettings/TagManager.asset
Labels: enhancement

#27 Docs/26 프로젝트 설명 페이지 초안 작성
  README.md
  docs/index.md
Labels: documentation

#28 Feature/23
  Assets/Private.meta
  Assets/Scenes/LobbyScene/ChampionSeclect.unity
  Assets/Scenes/LobbyScene/Lobby.unity
  Assets/Scripts/NetworkScripts/LobbyManager.cs
  Assets/Scripts/NetworkScripts/PrepareRoundManager.cs
  Assets/Scripts/NetworkScripts/PrepareRoundManager.cs.meta
Labels: enhancement
