Repository kookmin-sw/capstone-2022-06, pull requests merged in 2022-05, with the labels that each got.

#57 [변경] @Scene 오브젝트 추가
  Assets/Scenes/GameScene.unity
Labels: enhancement

#60 Issue/59 혼자서 게임에 입장하는 문제 해결
  Assets/Resources/Prefabs/UI/Scene/UI_Lobby.prefab
  Assets/Resources/Prefabs/UI/SubItem/UI_CancelButton.prefab
  Assets/Resources/Prefabs/UI/SubItem/UI_ConfirmButton.prefab
  Assets/Scripts/UI/Scene/UI_Lobby.cs
  Assets/Scripts/UI/Scene/UI_Preparation.cs
Labels: bug

#62 Issue/59 네트워킹을 고려하지 않아 생기는 문제 수습
  Assets/Resources/Data/HeroIcons.json
  Assets/Resources/Data/HeroIcons.json.meta
  Assets/Resources/Prefabs/UI/Scene/UI_Preparation.prefab
  Assets/Resources/Prefabs/UI/SubItem/UI_PortraitButton.prefab
  Assets/Scenes/Lobby/PreparationScene.unity
  Assets/Scripts/Data/PortraitButtonData.cs
  Assets/Scripts/JSON.meta
  Assets/Scripts/Manager/UIManager.cs
  Assets/Scripts/Scenes/GameScene.cs
  Assets/Scripts/Scenes/PreparationScene.cs
  Assets/Scripts/UI/Scene/UI_Lobby.cs
  Assets/Scripts/UI/Scene/UI_Preparation.cs
  ProjectSettings/EditorBuildSettings.asset
Labels: bug

#70 Feature/68 게임 경과 시간을 보여주는 UI 구현
  Assets/Resources/Prefabs/UI/Scene/UI_GameScene.prefab
  Assets/Scenes/GameScene.unity
  Assets/Scripts/Scenes/GameScene.cs
  Assets/Scripts/UI/Scene/UI_GameScene.cs
  Assets/Scripts/UI/Scene/UI_GameScene.cs.meta
  Assets/Scripts/UI/Scene/UI_Preparation.cs
Labels: enhancement

#75 Feature/73
  Assets/Resources/Prefabs/FootmanHP.prefab
  Assets/Scenes/GameScene.unity
  Assets/Scripts/MinionScripts/MinionController.cs
Labels: enhancement

#74 Feature/63 스폰 위치를 지정하는 코드 작성
  Assets/Scripts/Scenes/GameScene.cs
Labels: enhancement

#79 Feature/76 챔피언, 지휘관 구분에 따른 카메라 이동 기능 구현
  Assets/Scripts/Character/ClickMovement.cs
  Assets/Scripts/Character/PlayerHealthSlider.cs
  Assets/Scripts/Commander.meta
  Assets/Scripts/Commander/CommanderCamController.cs
  Assets/Scripts/Commander/CommanderCamController.cs.meta
  Assets/Scripts/Scenes/GameScene.cs
Labels: enhancement

#85 Feature/77 네트워크 환경에서 전장의 안개 구현
  Assets/Resources/Prefabs/Camera/Game/BirdEyeView.prefab
  Assets/Resources/Prefabs/ViewVisualisation.prefab
  Assets/Resources/Prefabs/ViewVisualisation.prefab.meta
  Assets/Scenes/GameScene.unity
  Assets/Scripts/Character/CamSwitchManager.cs
  Assets/Scripts/Character/FieldOfView.cs
  Assets/Scripts/Character/InputTargeting.cs
  Assets/Scripts/Character/LayerController.cs
  Assets/Scripts/Character/LayerController.cs.meta
  Assets/Scripts/Editor.meta
  Assets/Scripts/Editor/FieldOfViewEditor.cs
  Assets/Scripts/Editor/FieldOfViewEditor.cs.meta
  Assets/Scripts/ExLibrary/Util.cs
  Assets/Scripts/Manager/Managers.cs
  Assets/Scripts/Manager/VisibleManager.cs
  Assets/Scripts/MinionScripts/LichMinion.cs
  Assets/Scripts/MinionScripts/WaveManager.cs
  Assets/Scripts/Scenes/GameScene.cs
  Assets/Scripts/UI/WorldSpace/UI_Marker.cs
  ProjectSettings/TagManager.asset
Labels: enhancement

#95 Issue/93 전장의 안개 완벽 픽스
  Assets/Scripts/Character/LayerController.cs
  Assets/Scripts/ExLibrary/Util.cs
  Assets/Scripts/MinionScripts/WaveManager.cs
  Assets/Scripts/Scenes/GameScene.cs
Labels: bug

#102 Feature/78 지휘관 스킬창 UI 구현 완료
  Assets/Resources/Prefabs/UI/SubItem/UI_ChampSkill.prefab
  Assets/Resources/Prefabs/UI/SubItem/UI_ChampSkill.prefab.meta
  Assets/Resources/Prefabs/UI/SubItem/UI_ComSkill.prefab
  Assets/Resources/Prefabs/UI/SubItem/UI_ComSkill.prefab.meta
  Assets/Scenes/GameScene.unity
  Assets/Scripts/Scenes/GameScene.cs
  Assets/Scripts/UI/Effect.meta
  Assets/Scripts/UI/Effect/UI_Cooldown.cs
  Assets/Scripts/UI/Effect/UI_Cooldown.cs.meta
  Assets/Scripts/UI/Scene/UI_GameScene.cs
  Assets/Scripts/UI/Scene/UI_Lobby.cs
  Assets/Scripts/UI/SubItem/UI_ChampSkill.cs
  Assets/Scripts/UI/SubItem/UI_ChampSkill.cs.meta
  Assets/Scripts/UI/SubItem/UI_ComSkill.cs
  Assets/Scripts/UI/SubItem/UI_ComSkill.cs.meta
Labels: enhancement

#115 Feature/114 로비, 게임 준비 씬 배경 음악 추가
  Assets/Resources/Prefabs/UI/Scene/UI_Preparation.prefab
  Assets/Scenes/Lobby/LobbyScene.unity
  Assets/Scenes/Lobby/PreparationScene.unity
  Assets/Scripts/UI/Scene/UI_Preparation.cs
Labels: enhancement

#119 Feature/117 지휘관 기능 구현(미니언 한정)
  Assets/Scenes/Lobby/PreparationScene.unity
  Assets/Scripts/Define/Stats/ObjectStat.cs
  Assets/Scripts/ExLibrary/Util.cs
  Assets/Scripts/Particle/LeavesBuff.cs
  Assets/Scripts/Particle/Meteor.cs
  Assets/Scripts/Particle/ParticleBase.cs
  Assets/Scripts/UI/Effect/UI_Cooldown.cs
Labels: enhancement

#130 Feature/122 본부에 스탯 부여, 체력 UI 구현 완료
  Assets/Resources/Data/HQStatData.json
  Assets/Resources/Data/HQStatData.json.meta
  Assets/Scripts/Define/Stats/HQStat.cs
  Assets/Scripts/Define/Stats/HQStat.cs.meta
  Assets/Scripts/Manager/DataManager.cs
Labels: enhancement

#135 Feature/127 챔피언 스킬이 포톤 환경에서 작동되도록 변경
  Assets/Scripts/Character/Ability.cs
  Assets/Scripts/Character/THSSkill_EProj.cs
  Assets/Scripts/Character/THSSkill_RProj.cs
Labels: enhancement

#156 Feature/155 사망할 때 UI 출력
  Assets/Resources/Prefabs/UI/Scene/UI_DeadPanel.prefab
  Assets/Resources/Prefabs/UI/Scene/UI_DeadPanel.prefab.meta
  Assets/Scripts/Character/Ability.cs
  Assets/Scripts/Character/ChampionManager.cs
  Assets/Scripts/Character/ClickMovement.cs
  Assets/Scripts/Character/THSSkill_EProj.cs
  Assets/Scripts/Character/THSSkill_RProj.cs
  Assets/Scripts/Define/Stats/ObjectStat.cs
  Assets/Scripts/MinionScripts/MinionController.cs
  Assets/Scripts/Turret/TurretController.cs
  Assets/Scripts/UI/Scene/UI_DeadPanel.cs
  Assets/Scripts/UI/Scene/UI_DeadPanel.cs.meta
Labels: enhancement

#158 [변경] 영웅 목록 데이터 정리
  Assets/Resources/Data/HeroIcons.json
Labels: good first issue

#167 Feature/166 게임 종료 UI 구현
  Assets/Resources/Prefabs/UI/Scene/UI_Lobby.prefab
  Assets/Resources/Prefabs/UI/SubItem/UI_ExitMenuPopup.prefab
  Assets/Resources/Prefabs/UI/SubItem/UI_ExitMenuPopup.prefab.meta
  Assets/Scripts/UI/Scene/UI_GameScene.cs
  Assets/Scripts/UI/Scene/UI_Lobby.cs
  Assets/Scripts/UI/SubItem/UI_ExitMenuPopup.cs
  Assets/Scripts/UI/SubItem/UI_ExitMenuPopup.cs.meta
Labels: enhancement
